// 43 Categories for ResourceVault
export const CATEGORIES = [
  "Major Cloud Providers",
  "Cloud Management Solutions",
  "Source Code Repos",
  "APIs, Data, and ML",
  "Artifact Repos",
  "Tools for Teams and Collaboration",
  "CMS",
  "Code Generation",
  "Code Quality",
  "Code Search and Browsing",
  "CI and CD",
  "Testing",
  "Security and PKI",
  "Authentication, Authorization, and User Management",
  "Mobile App Distribution and Feedback",
  "Management System",
  "Messaging and Streaming",
  "Log Management",
  "Translation Management",
  "Monitoring",
  "Crash and Exception Handling",
  "Search",
  "Education and Career Development",
  "Email",
  "Feature Toggles Management Platforms",
  "Font",
  "Forms",
  "Generative AI",
  "CDN and Protection",
  "PaaS",
  "BaaS",
  "Low-code Platform",
  "Web Hosting",
  "DNS",
  "Domain",
  "IaaS",
  "Managed Data Services",
  "Tunneling, WebRTC, Web Socket Servers and Other Routers",
  "Issue Tracking and Project Management",
  "Storage and Media Processing",
  "Design and UI",
  "Design Inspiration",
  "Data Visualization on Maps",
  "Package Build System",
  "IDE and Code Editing",
  "Analytics, Events and Statistics",
  "Visitor Session Recording",
  "International Mobile Number Verification API and SDK",
  "Payment and Billing Integration",
  "Docker Related",
  "Dev Blogging Sites",
  "Commenting Platforms",
  "Screenshot APIs",
  "Flutter Related and Building IOS Apps without Mac",
  "Browser-based Hardware Emulation written in Javascript",
  "Privacy Management",
  "Miscellaneous",
  "Remote Desktop Tools",
  "Game Development",
  "Other Free Resources",
];
