// Category seed data - All unique categories from resources dataset
export const CATEGORIES = [
  "APIs, Data, and ML",
  "Authentication, Authorization, and User Management",
  "CI and CD",
  "Cloud Management Solutions",
  "Cloud Providers",
  "CMS",
  "Code Quality",
  "Code Search and Browsing",
  "Design and UI",
  "Education and Career Development",
  "Forms",
  "Log Management",
  "Managed Data Services",
  "Monitoring",
  "Search",
  "Security and PKI",
  "Source Code Repos",
  "Storage and Media Processing",
  "Testing",
  "Tools for Teams and Collaboration",
  "Web Hosting",
];
